# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\"|\n\x0bPlayerState\x12\n\n\x02hp\x18\x01 \x01(\x05\x12\x10\n\x08move_dir\x18\x02 \x01(\x02\x12\x0f\n\x07\x61im_dir\x18\x03 \x01(\x02\x12\x11\n\tis_moving\x18\x04 \x01(\x08\x12\x15\n\rshoot_cd_left\x18\x05 \x01(\x02\x12\x14\n\x0cterrain_info\x18\x06 \x03(\x02\".\n\nRegionInfo\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x10\n\x08\x64ir_info\x18\x02 \x01(\x05\"T\n\x06\x41\x63tion\x12\x10\n\x08move_dir\x18\x01 \x01(\x02\x12\x0f\n\x07\x61im_dir\x18\x02 \x01(\x02\x12\x12\n\nmove_state\x18\x03 \x01(\x08\x12\x13\n\x0bshoot_state\x18\x04 \x01(\x08\"\x9e\x01\n\nSensorData\x12\"\n\x0cplayer_state\x18\x01 \x01(\x0b\x32\x0c.PlayerState\x12\x1d\n\x08mob_data\x18\x02 \x03(\x0b\x32\x0b.RegionInfo\x12$\n\x0fmob_bullet_data\x18\x03 \x03(\x0b\x32\x0b.RegionInfo\x12\'\n\x12player_bullet_data\x18\x04 \x03(\x0b\x32\x0b.RegionInfo\"\x7f\n\tServerMsg\x12\x10\n\x08\x66ield_id\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08msg_type\x18\x03 \x01(\x05\x12 \n\x0bsensor_data\x18\x04 \x01(\x0b\x32\x0b.SensorData\x12\x0e\n\x06reward\x18\x05 \x01(\x02\x12\x10\n\x08game_end\x18\x06 \x01(\x08\"T\n\tClientMsg\x12\x10\n\x08\x66ield_id\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08msg_type\x18\x03 \x01(\x05\x12\x17\n\x06\x61\x63tion\x18\x04 \x01(\x0b\x32\x07.Action\"\x1c\n\rServerCtrlMsg\x12\x0b\n\x03\x63md\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERSTATE']._serialized_start=12
  _globals['_PLAYERSTATE']._serialized_end=136
  _globals['_REGIONINFO']._serialized_start=138
  _globals['_REGIONINFO']._serialized_end=184
  _globals['_ACTION']._serialized_start=186
  _globals['_ACTION']._serialized_end=270
  _globals['_SENSORDATA']._serialized_start=273
  _globals['_SENSORDATA']._serialized_end=431
  _globals['_SERVERMSG']._serialized_start=433
  _globals['_SERVERMSG']._serialized_end=560
  _globals['_CLIENTMSG']._serialized_start=562
  _globals['_CLIENTMSG']._serialized_end=646
  _globals['_SERVERCTRLMSG']._serialized_start=648
  _globals['_SERVERCTRLMSG']._serialized_end=676
# @@protoc_insertion_point(module_scope)
